#
# Defaults for Chezmoi features
#

feature_git = false

#
# Defaults for Chezmoi data files
#

gsettings_files = [ "./data/gsettings.json" ]
gnome_extensions_files = [ "./data/gnome-extensions.txt" ]
